config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),       # 관리자 페이지
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),  # users/urls.py를 추가
    path('', index),    # 경로가 없을 때 index View 연결
]
urlpatterns += static(      # 사용자가 업로드한 정적파일
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete

urlpatterns = [
  path('feeds/', feeds),
  path('comment_add/', comment_add),
  path('comment_delete/<int:comment_id>/', comment_delete),
]

users/urls.py
# app별로 urls.py 파일의 내용을 분리한다.
from django.urls import path
from users.views import login_view, logout_view, signup

urlpatterns = [
  path('login/', login_view),
  path('logout/', logout_view),
  path('signup/', signup),
]

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    # 'users.User' 모델을 참조하는 외래 키. Post는 특정 User에 속함.
    user = models.ForeignKey(
        'users.User',
        verbose_name='작성자',
        on_delete=models.CASCADE,   # 연관된 User가 삭제될 경우 해당 User의 모든 Post도 삭제됨을 의미.
    )
    # 포스트의 내용을 나타내는 텍스트 필드
    content = models.TextField('내용')
    # 포스트가 생성된 날짜 및 시간을 저장. 'auto_now_add=True'는 객체가 처음 생성될 때의 시간을 자동으로 설정.
    created = models.DateTimeField('작성일시', auto_now_add=True)


class PostImage(models.Model):
    # 'Post' 모델을 참조하는 외래 키. PostImage는 특정 Post에 속함.
    post = models.ForeignKey(
        Post,
        verbose_name='포스트',
        on_delete=models.CASCADE,   # 연관된 Post가 삭제될 경우 해당 Post의 모든 이미지도 삭제됨을 의미.
    )
    photo = models.ImageField('사진', upload_to='post')   # 이미지 파일을 저장하는 필드. 'upload_to'는 업로드된 파일이 저장될 경로를 설정.



class Comment(models.Model):
    # 'users.User' 모델을 참조하는 외래 키. Comment는 특정 User에 속함.
    user = models.ForeignKey(
        'users.User',
        verbose_name='작성자',
        on_delete=models.CASCADE,
    )
    # 'Post' 모델을 참조하는 외래 키. Comment는 특정 Post에 속함.
    post = models.ForeignKey(Post, verbose_name='포스트', on_delete=models.CASCADE)
    content = models.TextField('내용')
    created = models.DateTimeField('작성일시', auto_now_add=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
  '''
  AbstractUser는 Django가 CustomUser 모델을 만들기 위해 제공하는 기본 유저 형태를 가진 모델 클래스이다.
  이 클래스는 Django의 기본 User모델이 가진 필드를 똑같이 가지고 있으며, AbstractUser를 상속받으면 자동적으로 username, password, first_name, last_name, email, is_staff(관리자 여부), is_active(활성화 여부), date_joined, last_login 필드들이 모델에 추가된다.
  '''
  profile_image = models.ImageField(
    '프로필 이미지', upload_to='users/profile', blank=True
  )
  short_description = models.TextField('소개글', blank=True)   # 여기까지 하고, 모델을 변경했으므로 변경사항에 대한 migration을 생성하고 적용한다.

posts/forms.py
from django import forms
from posts.models import Comment

class CommentForm(forms.ModelForm):   # ModelForm 클래스 - Form클래스와 유사하나, DB 테이블에 해당하는 "모델 클래스"와 연관된 기능들을 제공한다.
  class Meta:
    model = Comment
    fields = [
      'post',
      'content',
    ]
    widgets = {
      'content': forms.Textarea(
        attrs={
          'placeholder': '댓글 달기...',
        }
      )
    }

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from users.models import User

class LoginForm(forms.Form):
  username = forms.CharField(
    min_length=3,
    widget=forms.TextInput(
      attrs={'placeholder': '사용자명 (3자리 이상)'},
    ),
  )
  password = forms.CharField(
    min_length=4,
    widget=forms.PasswordInput(
      attrs= {'placeholder': '비밀번호 (4자리 이상)'},
    ),
  )


class SignupForm(forms.Form):
  username = forms.CharField()
  password1 = forms.CharField(widget=forms.PasswordInput)   # 비밀번호
  password2 = forms.CharField(widget=forms.PasswordInput)   # 입력한 비밀번호 확인
  profile_image = forms.ImageField()
  short_description = forms.CharField()

  def clean_username(self):
    username = self.cleaned_data['username']    # 'username' 필드에 대한 유효성 검사
    if User.objects.filter(username=username).exists():
      raise ValidationError(f'입력한 사용자명({username})은 이미 사용 중입니다!')
    return username

  def clean(self):    # password1 & password2 검증
    password1 = self.cleaned_data['password1']
    password2 = self.cleaned_data['password2']
    if password1 != password2:
      self.add_error('password2', '비밀번호와 비밀번호 확인란의 값이 다릅니다!')

  def save(self):
    username=self.cleaned_data['username']
    password1 = self.cleaned_data['password1']
    profile_image = self.cleaned_data['profile_image']
    short_description = self.cleaned_data['short_description']
    user = User.objects.create_user(
      username=username,
      password=password1,
      profile_image=profile_image,
      short_description=short_description,
    )
    return user

config/views.py
from django.shortcuts import render, redirect

def index(request):
  if request.user.is_authenticated:
    return redirect('/posts/feeds/')
  else:
    return redirect('/users/login/')

posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post, Comment
from posts.forms import CommentForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden

# Create your views here.
def feeds(request):
  if not request.user.is_authenticated:
    # 사용자가 로그인하지 않은 경우, 로그인 페이지로 이동시킴
    return redirect('/users/login/')
  posts = Post.objects.all()
  comment_form = CommentForm()
  context = {
    'posts': posts,
    'comment_form': comment_form,
  }
  return render(request, 'posts/feeds.html', context)


@require_POST   # 댓글 작성을 처리할 View, Post 요청만 허용한다.
def comment_add(request):
  form = CommentForm(data=request.POST)
  if form.is_valid():
    comment = form.save(commit=False)   # commit = False 옵션으로 메모리상에 Comment 객체 생성
    comment.user = request.user   # Comment 생성에 필요한 사용자 정보를 request에서 가져와 할당
    comment.save()    # DB에 Comment 객체 저장
    print(comment.id)
    print(comment.content)
    print(comment.user)
    return HttpResponseRedirect(f'/posts/feeds/#post-{comment.post.id}')    # 생성 완료 후에는 피드 페이지로 다시 이동


@require_POST
def comment_delete(request, comment_id):
  if request.method == 'POST':
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
      comment.delete()
      return HttpResponseRedirect(f'/posts/feeds/#post-{comment.post.id}')
    else:
      return HttpResponseForbidden('이 댓글을 삭제할 권한이 없습니다.')

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from users.forms import LoginForm, SignupForm
from users.models import User

# Create your views here.
def login_view(request):
  # 이미 로그인되어 있다면 피드 페이지로 이동시킴
  if request.user.is_authenticated:
    return redirect('/posts/feeds/')

  if request.method == 'POST':
    form = LoginForm(data = request.POST)
    if form.is_valid():
      username = form.cleaned_data['username']
      password = form.cleaned_data['password']
      user = authenticate(username = username, password = password)

      if user:
        login(request, user)
        return redirect('/posts/feeds/')
      else:
        form.add_error(None, '입력한 자격증명에 해당하는 사용자가 없습니다.')
    context = {'form': form}
    return render(request, 'users/login.html', context)
  else:
    form = LoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)

def logout_view(request):
  logout(request)
  return redirect('/users/login/')

def signup(request):
  # POST 요청 시, form이 유효하다면 최종적으로 redirect 처리된다.
  if request.method == 'POST':
    form = SignupForm(data=request.POST, files=request.FILES)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('/posts/feeds/')
    # POST 요청에서 form이 유효하지 않다면, 아래의 context = ... 부분으로 이동한다.

  # GET 요청 시, 빈 form을 생성한다.
  else:
    form=SignupForm()

  # context로 전달되는 form은 두 가지 경우가 존재한다.
  # 1. POST 요청에서 생성된 form이 유효하지 않은 경우 - 에러를 포함한 form이 사용자에게 보여진다.
  # 2. GET 요청으로 빈 form이 생성된 경우 - 빈 form이 사용자에게 보여진다.
  context = {'form': form}
  return render(request, 'users/signup.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
  <script src="{% static 'splide/splide.js' %}"></script>
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <h1>pystagram</h1>
</body>
</html>

templates/posts/feeds.html
{% extends 'base.html' %}
{% block content %}
  <nav>
    <h1><a href="/posts/feeds/">Pystagram</a></h1>
    <a href="/users/logout/">Logout</a>
  </nav>
  <div id="feeds" class="post-container">
  <!-- 전달된 Post QuerySet 객체를 순회 -->
  {% for post in posts %}
    <article class="post" id="post-{{post.id}}">
      <header class="post-header">
        {% if post.user.profile_image %}
          <img src="{{post.user.profile_image.url}}">
        {% endif %}
        <span>{{post.user.username}}</span>
      </header>

      <!-- 이미지 슬라이드 영역 시작 -->
      <div class="post-images splide">
        <div class="post-content">
          {{post.content|linebreaksbr}}
        </div>
        <div class="post-buttons">
          <button>Likes(0)</button>
          <span>Comments({{post.comment_set.count}})</span>
        </div>
        <div class="post-comments">
          <ul>
            <!-- 각 Post에 연결된 PostComment들을 순회 -->
            {% for comment in post.comment_set.all %}
              <li>
                <span>{{comment.user.username}}</span>
                <span>{{comment.content}}</span>

                <!-- 댓글 삭제 form 추가 -->
                {% if user == comment.user %}   <!-- 현재 로그인된 사용자가 댓글의 작성자인지 확인 후 일치할 경우에만 삭제 버튼 만듦 -->
                <form action="/posts/comment_delete/{{comment.id}}/" method="POST">
                  {% csrf_token %}
                  <button type="submit">삭제</button>
                </form>
                {% endif %}
              </li>
            {% endfor %}
          </ul>
        </div>
        <small>{{post.created}}</small>
        <div class="post-comment-create">
          <form method="POST" action="/posts/comment_add/">
            {% csrf_token %}
            <input type="hidden" name="post" value="{{post.id}}">
            {{comment_form.content}}      <!-- 전달된 CommentForm의 필드들 중, 'content' 필드만 렌더링 -->
            <button type="submit">게시</button>
          </form>
        </div>
        <div class="splide__track">
          <ul class="splide__list">
            {% for image in post.postimage_set.all %}
              {% if image.photo %}
              <li class="splide__slide">
                <img src="{{image.photo.url}}">
              </li>
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
      <!-- 이미지 슬라이드 영역 종료 -->
    </article>
  {% endfor %}
  </div>
  <script>
    const elms = document.getElementsByClassName('splide')
    for (let i=0; i<elms.length; i++) {
      new Splide(elms[i]).mount();
    }
  </script>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div id="login">
  <form method="POST">
    <h1>Pystagram</h1>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-login">로그인</button>
    <a href="/users/signup/">회원가입 페이지로 이동</a>
  </form>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
<div id="signup">
  <form method="POST" enctype="multipart/form-data">   <!-- Template의 form은 파일(profile_image)의 전송을 포함하고 있으므로 form의 enctype 속성을 반드시 multipart/form-data로 정의해야 한다. -->
    <h1>Pystagram</h1>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-signup">가입</button>
    <a href="/users/login/">로그인 페이지로 이동</a>
  </form>
</div>
{% endblock %}